#ifndef __FP_VERSION_H__
#define __FP_VERSION_H__

#define FINGERPRINT_TA_VERSION_MAJOR 3
#define FINGERPRINT_TA_VERSION_MINOR 46

#if defined(AARCH64_SUPPORT)
#if defined(SIL_OPTICS)
#define FP_TA_VER ((FINGERPRINT_TA_VERSION_MAJOR+1+3)*100 + FINGERPRINT_TA_VERSION_MINOR)
#else
#define FP_TA_VER ((FINGERPRINT_TA_VERSION_MAJOR+3)*100 + FINGERPRINT_TA_VERSION_MINOR)
#endif /* SIL_OPTICS */
#else
#if defined(SIL_OPTICS)
#define FP_TA_VER ((FINGERPRINT_TA_VERSION_MAJOR+1)*100 + FINGERPRINT_TA_VERSION_MINOR)
#else
#define FP_TA_VER (FINGERPRINT_TA_VERSION_MAJOR*100 + FINGERPRINT_TA_VERSION_MINOR)
#endif /* SIL_OPTICS */
#endif /* AARCH64_SUPPORT */

#endif /* __FP_VERSION_H__ */
